2024 big update - unfinished

diff --git a/sudoedit-enhanced b/sudoedit-enhanced
--- a/sudoedit-enhanced
+++ b/sudoedit-enhanced
@@ -1,48 +1,69 @@
 #!/bin/sh
 
-#+------------------------------------------------------------------------------+
-#|                      Safe system files editing as root                       |
-#|                         Language: POSIX shell script                         |
-#|                    Copyright: 2020-2022 Vlastimil Burian                     |
-#|                        Email: info@vlastimilburian.cz                        |
-#|                              License: Unlicense                              |
-#|                         GitHub: https://git.io/Jvnzq                         |
-#|                                 Version: 4.0                                 |
-#|                            Released: 2022-Feb-26                             |
-#+------------------------------------------------------------------------------+
 
-# Customize these editor lists to your preference
-# before sourcing this script to your shell environment.
-conf__cli_editors='vi nano'
-conf__gui_editors='subl xed'
+## CONFIGURATION VARIABLES
+
+# You HAVE TO customize these space-delimited editor lists to your
+# preference before sourcing this script to your shell environment.
+___sudoedit__cli_editors='vi vim nano'
+___sudoedit__gui_editors='subl xed gedit'
+
+
+___sudoedit__script_intro=\
+'------------------------------------------------------------
+--           Safe system files editing as root            --
+--           Code language: POSIX shell script            --
+--         Copyright: 2020-2023 Vlastimil Burian          --
+--             Bugs: info@vlastimilburian.cz              --
+--              GitHub: https://git.io/Jvnzq              --
+--                 License: The Unlicense                 --
+--                 Version: 5.0 (stable)                  --
+--                 Released: 2023-Sep-30                  --
+------------------------------------------------------------'
+
 
 # We avoid generating editor aliases for which an editor is not installed.
 # We avoid generating editor aliases for which we already have an alias.
 
-# CLI alias generator:
-for cli_editor in $conf__cli_editors; do
+
+for cli_editor in $___sudoedit__cli_editors; do
+
     if command -v "$cli_editor" >/dev/null 2>&1; then
+
         if [ -z "$(alias "su$cli_editor" 2>/dev/null)" ]; then
+
             # shellcheck disable=SC2139,SC2086
             alias su$cli_editor="sudoedit_run cli $cli_editor"
-        fi
-    fi
-done
 
-# GUI alias generator:
-for gui_editor in $conf__gui_editors; do
+        fi
+
+    fi
+
+done
+unset cli_editor
+
+
+for gui_editor in $___sudoedit__gui_editors; do
+
     if command -v "$gui_editor" >/dev/null 2>&1; then
+
         if [ -z "$(alias "su$gui_editor" 2>/dev/null)" ]; then
+
             # shellcheck disable=SC2139,SC2086
             alias su$gui_editor="sudoedit_run gui $gui_editor"
+
         fi
+
     fi
+
 done
+unset gui_editor
+
 
 # NON-COMPLIANT-GUI EXAMPLES:
 # * code -w --user-data-dir; I did not find a way to run it through sudoedit
 # * atom -w --no-sandbox
-# * gedit -w does not work via rooted ssh
+# * gedit -w does not work via rooted ssh, but works locally, so I include it
 # * pluma does not have -w switch
 #
 # Description: This script works with standard sudoedit, but
@@ -66,27 +87,104 @@ done
 # sunano /path/to/file
 # susubl /path/to/file
 
+
+# Print intro only the first time `sudoedit_run` or any alias alone is called.
+___sudoedit_print_intro ()
+{
+    if [ -n "$___sudoedit__script_intro" ]; then
+
+        # Upon the first call the intro is printed;
+        # corresponding variable is emptied. And
+        # True is returned from the function.
+
+        printf '%s\n' "$___sudoedit__script_intro"
+        ___sudoedit__script_intro=
+        return 0
+
+    else
+
+        return 1
+
+    fi
+}
+
+
+# Usage function contains very basic information about this script.
+___sudoedit_print_usage ()
+{
+    cat <<EOF
+This script needs to be sourced into your
+shell's environment first; for example in
+
+- Bash: source /path/to/sudoedit-enhanced
+- POSIX:   .   /path/to/sudoedit-enhanced
+
+Usage of sudoedit-enhanced shell extension.
+Example: suvi /path/to/file1 /path/to/file2
+EOF
+}
+
+
+
+
+
+
+
+
+
+# Alias print function
+___sudoedit_print_alias ()
+{
+    printf '%s\n' 'This shell extension has defined' \
+                  'the following su-editor aliases:'
+
+    printf '\n%s' 'CLI: '
+    if [ -z "$___sudoedit__cli_editors" ]; then
+        printf '%s' '<none>'
+    fi
+    for editor in $___sudoedit__cli_editors; do
+        if command -v "$editor" >/dev/null 2>&1; then
+            if [ -n "$(alias "su$editor" 2>/dev/null)" ]; then
+                printf '%s  ' "su$editor"
+            fi
+        fi
+    done
+
+    printf '\n%s' 'GUI: '
+    if [ -z "$___sudoedit__gui_editors" ]; then
+        printf '%s' '<none>'
+    fi
+    for editor in $___sudoedit__gui_editors; do
+        if command -v "$editor" >/dev/null 2>&1; then
+            if [ -n "$(alias "su$editor" 2>/dev/null)" ]; then
+                printf '%s  ' "su$editor"
+            fi
+        fi
+    done
+
+    unset editor
+
+    printf '\n'
+}
+
 sudoedit_run ()
 {
-    # Print usage if called with 2 arguments.
+    # Print usage if the function is called with less or equal to 2 arguments.
     if [ "$#" -le 2 ]; then
-        printf '%s\n\n' 'Usage example: sueditor /path/to/file1 /path/to/file2'
-        printf '%s\n' 'sudoedit-enhanced defined the following editors:'
-        for editor in $conf__cli_editors $conf__gui_editors; do
-            if command -v "$editor" >/dev/null 2>&1; then
-                if [ -n "$(alias "su$editor" 2>/dev/null)" ]; then
-                    printf '%s  ' "su$editor"
-                fi
-            fi
-        done
+        if ___sudoedit_print_intro; then
+            printf '\n'
+        fi
+        ___sudoedit_print_usage
         printf '\n'
+        ___sudoedit_print_alias
         return 0
     fi
 
     # sudo must be installed.
     if ! command -v sudo >/dev/null 2>&1; then
-        printf >&2 '%s\n' "'sudo' is required by this function. This is because" \
-                          "'sudoedit' is part of 'sudo'\`s edit feature (sudo -e)."
+        # shellcheck disable=SC2016
+        printf >&2 '%s\n' '`sudo` is required by this function. This is because' \
+                          '`sudoedit` is part of `sudo`'\''s edit feature (`sudo -e`).'
         return 1
     fi
 
@@ -94,7 +192,8 @@ sudoedit_run ()
     case "$1" in
         (cli|gui)
         ;;
-        (*) printf >&2 '%s\n' "'$1' is unrecognized editor type, expected 'cli' or 'gui'."
+        (*)
+            printf >&2 '%s\n' "'$1' is unrecognized editor type, expected 'cli' or 'gui'."
             return 1
         ;;
     esac
@@ -105,7 +204,7 @@ sudoedit_run ()
     shift 2
 
     # Find and store path to this editor.
-    editor_path=$(command -v "$editor_name" 2>/dev/null)
+    editor_path=$( command -v "$editor_name" 2>/dev/null )
 
     # Check if such editor, ie. executable path exists.
     if [ ! -x "$editor_path" ]; then
@@ -113,37 +212,60 @@ sudoedit_run ()
         return 1
     fi
 
-    # sudoedit does not work with symlinks;
-    # Translating symlinks to normal file paths using readlink - if available.
+    # Translating symlinks to normal file paths using `readlink` - if available.
     if command -v readlink >/dev/null 2>&1; then
+
         for file in "$@"; do
+
             if [ -L "$file" ]; then
-                if ! file=$(readlink -f "$file"); then
-                    printf >&2 '%s\n' "readlink -f $file failed."
+
+                if ! file=$( readlink -e "$file" ); then
+                    printf >&2 '%s\n' "readlink -e '$file' failed."
                     return 1
                 fi
+
+                set -- "$@" "$file"
+                shift
+
             fi
-            set -- "$@" "$file"
-            shift
+
         done
+
+    else
+        # shellcheck disable=SC2016
+        printf >&2 '%s\n' 'Warning: `sudoedit` does not work with symlinks, but `readlink` is not available.'
     fi
 
+    # Test every file to be regular files. Must be possible to create new file(s).
+    for file in "$@"; do
+
+        if [ -e "$file" ] && [ ! -f "$file" ]; then
+            printf >&2 '%s\n' "File $file is not a regular file. Quiting to shell..."
+            return 1
+        else
+            set -- "$@" "$file"
+            shift
+        fi
+
+    done
+
+
     # - GUI editors sit on the terminal until closed thanks to the wait option which we require.
-    #   For example xed and others flood the terminal with errors, so we redirect all output,
+    #   For example xed and others flood the terminal with errors, so we redirect all output
     #   into prepared temporary file in order to filter possible "sudoedit: file unchanged" lines.
     # - CLI editors work as expected without any customizations needed.
     if [ "$editor_type" = gui ]; then
 
         # GUI step 1) We try to determine the location of a temporary directory.
         tmpdir=${TMPDIR:-/tmp}
-        if [ ! -d "$tmpdir" ]; then
+        if [ ! -d "$tmpdir" ] || [ ! -w "$tmpdir" ]; then
             # shellcheck disable=SC2016
-            printf >&2 '%s\n' '${TMPDIR:-/tmp} failed to get a temporary directory.'
+            printf >&2 '%s\n' '${TMPDIR:-/tmp} failed to get a writable temporary directory.'
             return 1
         fi
 
         # GUI step 2) We try to create a temporary file inside the temporary directory.
-        tmpfile=$(mktemp "$tmpdir/sudoedit_run_gui.XXXXXX")
+        tmpfile=$( mktemp "$tmpdir/sudoedit_run_gui.XXXXXX" )
         if [ ! -f "$tmpfile" ]; then
             printf >&2 '%s\n' "mktemp $tmpdir/sudoedit_run_gui.XXXXXX failed to get a temporary file."
             return 1
@@ -156,17 +278,21 @@ sudoedit_run ()
         SUDO_EDITOR="$editor_path -w" sudoedit -- "$@" >"$tmpfile" 2>&1
         sudoedit_return_code=$?
 
-        # When using grep, it is important to escape it for there is usually some alias.
+        # When using grep, it is important to escape it for there is usually an alias.
         # shellcheck disable=SC1007
         GREP_COLORS= GREP_COLOR= GREP_OPTIONS= \grep sudoedit "$tmpfile"
-        rm "$tmpfile"
+        rm -f "$tmpfile"
+
+        unset editor_name editor_path editor_type tmpdir tmpfile
 
         # It is imperative to return with sudoedit's return code, and not rm's or something else.
         return "$sudoedit_return_code"
+
     else
         # CLI editors do not cause problems mentioned above.
         # This is a generic and proper way using sudoedit;
         # Running the editor with one-time SUDO_EDITOR setup.
         SUDO_EDITOR="$editor_path" sudoedit -- "$@"
     fi
+
 }
